name: Android CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Descomprime el proyecto que subiste como ZIP
      - name: Unzip project
        run: |
          unzip PlantasSamuel_Starter.zip -d .
          mv PlantasSamuel/* .
          rm -rf PlantasSamuel

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # SDK de Android (API 34 y build-tools 34.0.0)
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: |
            platforms;android-34
            build-tools;34.0.0

      # Alinea la versión del compilador de Compose con Kotlin 2.0
      - name: Patch Compose Compiler version
        run: |
          sed -i 's/kotlinCompilerExtensionVersion = "1.5.15"/kotlinCompilerExtensionVersion = "1.6.10"/' app/build.gradle.kts

      # Instala Gradle 8.7 y compila el APK (sin wrapper)
      - name: Install Gradle 8.7
        run: |
          curl -sLo gradle.zip https://services.gradle.org/distributions/gradle-8.7-bin.zip
          mkdir -p $HOME/gradle && unzip -q gradle.zip -d $HOME/gradle
          echo "$HOME/gradle/gradle-8.7/bin" >> $GITHUB_PATH

      - name: Build Debug APK
        run: gradle :app:assembleDebug

      - name: Publicar APK como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
