name: Android CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1) Descomprimir el proyecto que subiste como ZIP
      - name: Unzip project
        run: |
          unzip PlantasSamuel_Starter.zip -d .
          mv PlantasSamuel/* .
          rm -rf PlantasSamuel

      # 2) JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # 3) Instalar manualmente Android cmdline-tools y paquetes necesarios
      - name: Install Android SDK (cmdline-tools + packages)
        env:
          ANDROID_SDK_ROOT: ${{ runner.temp }}/android-sdk
        run: |
          set -e
          mkdir -p "$ANDROID_SDK_ROOT/cmdline-tools"
          curl -sLo cmdline-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          unzip -q cmdline-tools.zip -d "$ANDROID_SDK_ROOT/cmdline-tools"
          mv "$ANDROID_SDK_ROOT/cmdline-tools/cmdline-tools" "$ANDROID_SDK_ROOT/cmdline-tools/latest"
          yes | "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" --sdk_root="$ANDROID_SDK_ROOT" --licenses
          yes | "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" --sdk_root="$ANDROID_SDK_ROOT" \
            "platform-tools" "platforms;android-34" "build-tools;34.0.2"

      # 4) Ajuste de versión del compilador de Compose para Kotlin 2.0
      - name: Patch Compose Compiler version
        run: |
          sed -i 's/kotlinCompilerExtensionVersion = "1.5.15"/kotlinCompilerExtensionVersion = "1.6.10"/' app/build.gradle.kts

      # 5) Instalar Gradle 8.7 y compilar
      - name: Install Gradle 8.7
        run: |
          curl -sLo gradle.zip https://services.gradle.org/distributions/gradle-8.7-bin.zip
          mkdir -p $HOME/gradle && unzip -q gradle.zip -d $HOME/gradle
          echo "$HOME/gradle/gradle-8.7/bin" >> $GITHUB_PATH

      - name: Build Debug APK
        env:
          ANDROID_SDK_ROOT: ${{ runner.temp }}/android-sdk
          ANDROID_HOME: ${{ runner.temp }}/android-sdk
        run: gradle :app:assembleDebug --no-daemon

      # 6) Publicar el APK
      - name: Publicar APK como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
